// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv263luBeIJ3dJNuhAeAPdqvo2447PIss',
    appId: '1:213059744911:web:a26d7fb5ddf8b0ff46acfa',
    messagingSenderId: '213059744911',
    projectId: 'wtnb-spotify-clone-app',
    authDomain: 'wtnb-spotify-clone-app.firebaseapp.com',
    storageBucket: 'wtnb-spotify-clone-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkQEenscQ3F5SdYTDNtE6vdjoHZdtd-Fo',
    appId: '1:213059744911:android:4fac8eb7bd622e3b46acfa',
    messagingSenderId: '213059744911',
    projectId: 'wtnb-spotify-clone-app',
    storageBucket: 'wtnb-spotify-clone-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBptxakv2Zz-UE9m9cG2AYNlVb4Qa78j2o',
    appId: '1:213059744911:ios:0c4c9b1a1b9820fc46acfa',
    messagingSenderId: '213059744911',
    projectId: 'wtnb-spotify-clone-app',
    storageBucket: 'wtnb-spotify-clone-app.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBptxakv2Zz-UE9m9cG2AYNlVb4Qa78j2o',
    appId: '1:213059744911:ios:0c4c9b1a1b9820fc46acfa',
    messagingSenderId: '213059744911',
    projectId: 'wtnb-spotify-clone-app',
    storageBucket: 'wtnb-spotify-clone-app.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv263luBeIJ3dJNuhAeAPdqvo2447PIss',
    appId: '1:213059744911:web:1b28f0ebe519900f46acfa',
    messagingSenderId: '213059744911',
    projectId: 'wtnb-spotify-clone-app',
    authDomain: 'wtnb-spotify-clone-app.firebaseapp.com',
    storageBucket: 'wtnb-spotify-clone-app.firebasestorage.app',
  );
}
